### ISSUE TITLE
Should there be a separate app or this be integrated in radio4000-cms

### ISSUE THREAD

**Issue by hugurp** [internet4000/radio4000-export#2]
Sometime I think that just a button in your `channel/edit` route would be cool.

Anyways we have to put a button/link somewhere in the r4-cms to point to the action.

If this link points to `export.radio4000.com`, then you'd either have to enter your channel slug, but we can also open a link there to the channel already loaded.

What do we offer?

Downloads a json with all your channel data, and tracks embeded.

Is there anything more to this?

**Comment by oskarrough** [comment]
No, I think that's it. You get JSON with all relevant data + text to copy/paste. A link to download the original avatar as well perhaps?

My vote goes to

- deploy it as a seperate app on `export.radio4000.com`
- add support for slug via URL (preferably like on r4 `export.radio4000.com/my-slug`)
- link to it from R4 (edit page?)

This way you can prefix any radio URL with `export` and there you are. No need to adapt to Ember.… although that's also a fair solution but not one I'm super interested in since this seperate version already mostly works.

**Comment by hugurp** [comment]
Alright, let's go with that.

**Comment by hugurp** [comment]
![deepinscreenshot_select-area_20180221164231](https://user-images.githubusercontent.com/1502484/36489335-13133488-1726-11e8-934b-cc3ab8094831.png)
Fig1. one button, calls an API endpoint that generates the data
